import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Shared/Molecules/Navbar/Navbar'
import ToasterComponent from './components/Shared/Atoms/ToasterComponent/ToasterComponent'
import { Suspense } from 'react'
import Loading from './loading'
import StoreProvider from './StoreProvider'
import BackButton from './components/Shared/Molecules/BackButton/BackButton'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-[100vh]`}>
        <StoreProvider>
          <Navbar />
          <Suspense fallback={<Loading />}>
            <main className="min-h-full flex flex-col items-center gap-10 py-10 px-7 sm:px-10 md:px-20 relative">
              <BackButton />
              {children}
            </main>
          </Suspense>
          {/* {children} */}
          <ToasterComponent />
        </StoreProvider>
      </body>
    </html>
  )
}
